Update config file specification format
nasa/OnAIR pull request #128
Opened 2024-03-23 02:08 UTC by dragonejt

# Description
* Updates the config `.ini` file specification format used by OnAIR to follow the requirements of #101 
* Updates execution engine config file parser to read correct keys
* Updates execution enginer unit tests to provide valid fake data

# Testing
* `python driver.py` ran with no errors
* `python driver.py -t` (all unit tests) succeeded

# Considerations
* I had used VSCode's autoformatter to format `test_execution_engine.py` when updating the fake data to verify the fake data was nested correctly. If we want to go back to the original format for some reason I can figure something out to revert the formatting, but as an action item I can also take a look at adding a linter and autoformatter if we want to ensure a consistent code style.
* I had posted a comment in #101 about it being difficult to find any references for the `.ini` file specification. Has it been considered to move to a more modern/commonly used python configuration file format such as [TOML](https://toml.io/en/) (which visually appears very similar to `.ini`)? Python has a built-in library for reading TOML files as well, and modern python libraries use a `pyproject.toml` file for configurations.

2024-03-31 19:30 UTC, dragonejt commented
@the-other-james @asgibson just in case y'all haven't seen this PR, I updated the config file specification format to what was wanted in #128

2024-04-01 12:54 UTC, asgibson commented
@dragonejt at a glance your coding looks very good, but my formal review will take a little more time. After my review, it will need a secondary review before a merge. There are two reviews ahead in the pipeline #125 and #127 (#98 is on hold).

In your comment, you mention #128, but as this comment is in 128, I assume you mean the issue #101. In my cursory review you appear to be hitting all the marks on the requests in that issue. While awaiting the formal review, are you able to create a feature branch for #101 and rebase it to branch [126](https://github.com/nasa/OnAIR/tree/126-provide-some-backwards-compatibility-with-previous-python-versions)? We like to use branches for issue tracking and the rebase will make merging smoother after the other PRs are complete.

Thank you very much for your time and effort, it is appreciated!

2024-04-01 14:37 UTC, dragonejt commented
Sorry, yes I meant that this PR addresses #101 . Unfortunately, as I am not a collaborator on this repository I cannot create new branches on the repo or push to any branch on the repo. Instead, I forked the repository and submitted the PR from the fork to the original, as that was the guidance from [reading this](https://github.com/nasa/instructions/blob/master/docs/INSTRUCTIONS.md). There is the option  to be added as a collaborator to the repository on a case-by-case basis if that is something that we want to pursue. Otherwise, the best I can do is currently what is being done, which is forking the repo and submitting the PR from my fork onto the original repository.

2024-04-01 14:55 UTC, asgibson commented
No worries, I thought that may be the case. Thank you for looking into it.

2024-04-19 19:51 UTC, the-other-james requested changes
Great work! And thank you for your patience with us!

Before I approve, please update the branch you are merging in to have the latest from our main. I think there are likely conflicts with the redis .ini file since Alan had made updates.

Also, please address my annoying nitpicks about formatting :)

Thanks!

2024-04-19 20:03 UTC, the-other-james commented on onair/src/run_scripts/execution_engine.py
> +            self.parse_data(self.data_source_file,
Nevermind... leave the line breaks as you have them: Alan pointed out that https://peps.python.org/pep-0008/#maximum-line-length has the max as 79 characters.

2024-04-19 21:16 UTC, asgibson requested changes
Good work! All 8 of the requested changes in #101 are addressed.
Some minor changes to make, but overall looks great.

2024-04-19 21:16 UTC, asgibson commented on onair/src/run_scripts/execution_engine.py
> +                config_filepath}', missing key: {e.args[0]}"
f-string does not allow splitting lines < Python 3.12
We are currently supporting Python 3.8-3.12. 
Suggest we allow the long lines or we'll need to end strings with \ (as well as not using the / within the braces {}) AND begin the next line left justified.
```
        new_message = f"Config file: '\
{config_filepath}', missing key: {e.args[0]}"
```

2024-04-19 21:16 UTC, asgibson commented on onair/src/run_scripts/execution_engine.py
> +                             self.config_filepath} is invalid. It must be a dict.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:16 UTC, asgibson commented on onair/src/run_scripts/execution_engine.py
> +                                        plugin_file}' does not exist.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:16 UTC, asgibson commented on test/onair/src/run_scripts/test_execution_engine.py
> +                        arg_bad_config_filepath}' could not be read.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:16 UTC, asgibson commented on test/onair/src/run_scripts/test_execution_engine.py
> +                        fake_config_filepath} is invalid. It must be a dict.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:16 UTC, asgibson commented on test/onair/src/run_scripts/test_execution_engine.py
> +                        fake_path}' does not exist.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:16 UTC, asgibson commented on test/onair/src/run_scripts/test_execution_engine.py
> +                        fake_path}' does not exist.")
f-string does not allow splitting lines < Python 3.12

2024-04-19 21:18 UTC, asgibson commented on .gitignore
> +.vscode/
That I do.

2024-04-28 22:14 UTC, dragonejt commented
Sorry for the delay, I've been busy. I'll work on these changes over the next few weeks and submit a revision.

2024-06-15 17:52 UTC, dragonejt commented
Hey sorry I haven't gotten to revising this PR, I'm going to address the comments here over the next week or so. Are there any updates to how we use the .ini file that need to be reflected in this PR? Also, looking at the formatting changes requested, I was thinking about bringing in a Python code formatter so that I didn't need to manually format the codebase, such as [black](https://github.com/psf/black) or [Ruff](https://docs.astral.sh/ruff/). Is there any reason I should not use an autoformatter?

2024-06-18 03:58 UTC, dragonejt commented
## Rev 2
* Remove `Dev_enabled` and `Viz_enabled` feature flags
* Format with `black` to achieve a consistent code style, future code can be formatted with `black .`. This also removes the multiline f-strings.
* Add all items in GitHub's default python .gitignore with a newline at the bottom. This covers all files previously ignored, and more files that we should probably ignore.
* Updated a unit test failure by changing how a class instance was created, please let me know if we need to change it back
```
FAILED test/onair/src/run_scripts/test_execution_engine.py::test_ExecutionEngine_parse_configs_skips_OPTIONS_when_the_required_section_OPTIONS_is_not_in_config - AttributeError: 'ExecutionEngine' object has no attribute 'IO_Enabled'
```
I believe `__new__` doesn't actually call `__init__`, so changing it to how normal class instances are created calls `__init__`.

Most of the changes are in `execution_engine.py` and `test_execution_engine.py`, the rest of the files changed should all be formatting. If we want to remove code formatting changes, I can remove this commit and just do one without the formatting.

## Testing
All Unit Tests succeeded.

2024-06-20 17:59 UTC, the-other-james commented
Could you please remove the changes related to formatting? I don't want to mix formatting changes in with your other changes: it makes for a huge pull request (62 changed files) which obfuscates the config file update.

Reformatting of the entire code base should be done as its own pull request. Alan started looking into this a while ago: https://github.com/nasa/OnAIR/pull/98

2024-06-21 02:33 UTC, dragonejt commented
A no-formatting revision has been pushed.

2024-06-27 23:21 UTC, dragonejt commented
Just in case you two haven't seen this, @the-other-james @asgibson

2024-07-10 16:28 UTC, the-other-james approved these changes
Looks good to me! Tested default config and unit tests on my machine.

2024-07-10 16:57 UTC, the-other-james requested changes
I did a bit more testing and noticed that the kalman and redis configs hadn't been fully updated. I'm not sure if I can directly push my fixes to your merge request, so here's the diff that got things working on my end:

```
diff --git a/onair/config/kalman_csv_output_example.ini b/onair/config/kalman_csv_output_example.ini
index 06dab42..a1c927d 100644
--- a/onair/config/kalman_csv_output_example.ini
+++ b/onair/config/kalman_csv_output_example.ini
@@ -1,14 +1,17 @@
-[DEFAULT]
-TelemetryDataFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
+[FILES]
+TelemetryFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
 TelemetryFile = 700_crash_to_earth_1.csv
-TelemetryMetadataFilePath = onair/data/telemetry_configs/
+MetaFilePath = onair/data/telemetry_configs/
 MetaFile = data_physics_generation_CONFIG.json
-ParserFileName = onair/data_handling/csv_parser.py

+[DATA_HANDLING]
+DataSourceFile = onair/data_handling/csv_parser.py
+
+[PLUGINS]
 KnowledgeRepPluginDict = {'Kalman Filter': 'plugins/kalman'}
 LearnersPluginDict = {'csv output':'plugins/csv_output'}
 PlannersPluginDict = {}
 ComplexPluginDict = {}

-[RUN_FLAGS]
-IO_Flag = true
+[OPTIONS]
+IO_Enabled = true
diff --git a/onair/config/redis_example.ini b/onair/config/redis_example.ini
index b0a599b..3f70e42 100644
--- a/onair/config/redis_example.ini
+++ b/onair/config/redis_example.ini
@@ -3,7 +3,9 @@ TelemetryFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
 TelemetryFile = 700_crash_to_earth_1.csv
 MetaFilePath = onair/data/telemetry_configs/
 MetaFile = redis_example_CONFIG.json
-ParserFileName = onair/data_handling/redis_adapter.py
+
+[DATA_HANDLING]
+DataSourceFile = onair/data_handling/redis_adapter.py

 [PLUGINS]
 KnowledgeRepPluginDict = {'knowledge':'plugins/generic/__init__.py'}
```

2024-07-10 16:59 UTC, dragonejt commented
> I did a bit more testing and noticed that the kalman and redis configs hadn't been fully updated. I'm not sure if I can directly push my fixes to your merge request, so here's the diff that got things working on my end:
> 
> ```
> diff --git a/onair/config/kalman_csv_output_example.ini b/onair/config/kalman_csv_output_example.ini
> index 06dab42..a1c927d 100644
> --- a/onair/config/kalman_csv_output_example.ini
> +++ b/onair/config/kalman_csv_output_example.ini
> @@ -1,14 +1,17 @@
> -[DEFAULT]
> -TelemetryDataFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
> +[FILES]
> +TelemetryFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
>  TelemetryFile = 700_crash_to_earth_1.csv
> -TelemetryMetadataFilePath = onair/data/telemetry_configs/
> +MetaFilePath = onair/data/telemetry_configs/
>  MetaFile = data_physics_generation_CONFIG.json
> -ParserFileName = onair/data_handling/csv_parser.py
> 
> +[DATA_HANDLING]
> +DataSourceFile = onair/data_handling/csv_parser.py
> +
> +[PLUGINS]
>  KnowledgeRepPluginDict = {'Kalman Filter': 'plugins/kalman'}
>  LearnersPluginDict = {'csv output':'plugins/csv_output'}
>  PlannersPluginDict = {}
>  ComplexPluginDict = {}
> 
> -[RUN_FLAGS]
> -IO_Flag = true
> +[OPTIONS]
> +IO_Enabled = true
> diff --git a/onair/config/redis_example.ini b/onair/config/redis_example.ini
> index b0a599b..3f70e42 100644
> --- a/onair/config/redis_example.ini
> +++ b/onair/config/redis_example.ini
> @@ -3,7 +3,9 @@ TelemetryFilePath = onair/data/raw_telemetry_data/data_physics_generation/Errors
>  TelemetryFile = 700_crash_to_earth_1.csv
>  MetaFilePath = onair/data/telemetry_configs/
>  MetaFile = redis_example_CONFIG.json
> -ParserFileName = onair/data_handling/redis_adapter.py
> +
> +[DATA_HANDLING]
> +DataSourceFile = onair/data_handling/redis_adapter.py
> 
>  [PLUGINS]
>  KnowledgeRepPluginDict = {'knowledge':'plugins/generic/__init__.py'}
> ```

Ah, I may have not fully changed the other configs, sorry about that. I'll get that fixed

2024-07-10 17:53 UTC, dragonejt commented
@the-other-james It looks like what happened was that I did indeed miss the error in `redis_example.ini`, but the commit that added `onair/config/kalman_csv_output_example.ini` took place after I created my fork from the main repo, so my fork didn't have that file. The new commit I just pushed has the updates, and should work now.

2024-07-11 15:35 UTC, asgibson requested changes
Please revert the ExecutionEngine instantiations in the unit tests. By only allocating space for the instances it makes the tests more maintainable because changes in the `__init__` function will not affect the tests (as it will not run). This also requires the tests to explicitly set any attributes within the test itself because initialization was not performed on the instance, which provides more information about how the code under test (cut) operates.

2024-07-11 22:00 UTC, dragonejt commented on test/onair/src/run_scripts/test_execution_engine.py
> +    cut = ExecutionEngine()
I didn't realize that some of the tests were testing `__init__`, this has since been reverted and all instantiations should be calling `__new__`.

2024-07-11 22:01 UTC, dragonejt commented on .gitignore
This .gitignore is the GitHub default gitignore, and is generated in any new Python GitHub repository: https://github.com/github/gitignore/blob/main/Python.gitignore

I noticed that `.DS_Store` for macOS was missing from the changed `.gitignore`, so I re-added that.

2024-07-14 18:29 UTC, dragonejt commented
@asgibson the ExecutionEngine issue has been fixed, and I left a comment about where I got my Python .gitignore from. Please take a look when you have time.

2024-07-26 16:40 UTC, asgibson approved these changes

2024-07-26 16:44 UTC, the-other-james approved these changes
Great work! Thank you for you patience!

2024-07-26 19:05 UTC, dragonejt commented
Hello, I don't have permissions to merge into the main branch, so one of you will need to merge whenever we're ready to merge.

2024-07-26 21:27 UTC, merged