158 add ability for plugin pipeline external persistent processes
nasa/OnAIR pull request #167
Opened 2024-11-14 15:34 UTC by cfirth-nasa

Services framework has been implemented and unit tests have been updated to cover modifications. Currently, no example services are provided. Deferring to reviewers on whether we ought to wait for an example to be implemented (and tested) before adding to the main branch. This Services implementation is expected to be fully backwards compatible with previous OnAIR implementations.

2024-11-26 20:54 UTC, the-other-james commented on test/onair/src/util/test_singleton.py
> +    assert instance1 is instance2
I like that this test perfectly describes "singleton" functionally.

2024-11-26 20:57 UTC, the-other-james commented
Confirmed that tests pass and coverage is 100% on my setup. Code looks good to me (but I wasn't checking for docstrings...).

I created https://github.com/nasa/OnAIR/issues/176 to capture that we still need an example and docs for how to create and use a service.

Great work!

2024-11-27 17:20 UTC, the-other-james commented
@asgibson and I were discussing how plugins access services and want to avoid the user having to explicitly "instantiate" the services singleton.
Would it make sense to update the AI_plugin init function (https://github.com/nasa/OnAIR/blob/main/onair/src/ai_components/ai_plugin_abstract/ai_plugin.py#L20) with the services instantiationg? And then the plugin can just access via something like 'self.services'? Similar to how all plugins have access to headers, the list of telemetry point names.

2024-12-09 17:21 UTC, cfirthae commented
Large update... ServiceManager is now instantiated in the AIPlugin superclass, meaning Plugins can access it by `self.service_manager`. 

This change necessitated a bunch of fixes in the CSV Output example plugin's unit tests since the way those are written is out of date. Preliminary changes to that set of tests were made so it would pass, but they will need a full overhaul eventually - I'll make a new issue.

Merged commits to take advantage of more recent updates to the Pylint pipeline. 

We should be good to go!

2024-12-09 21:52 UTC, asgibson requested changes
Needs a clean rebase with main.

2024-12-11 18:56 UTC, cfirthae commented on onair/services/service_manager.py
> +        Returns dictionary of services and their functions.
> Please remove the Methods section. We can keep the class definitions to just the description and Attributes section.

Fixed!

2025-01-02 23:07 UTC, asgibson approved these changes
Everything I did not do is approved.
Someone will need to review my updates.

2025-01-03 14:36 UTC, the-other-james approved these changes
Looks good to me! Double checked on my system: unit tests pass and coverage is 100%.

2025-01-03 21:19 UTC, cfirthae approved these changes
Works and passes on my system!

2025-01-03 21:24 UTC, merged