177 finish kalman tutorial
nasa/OnAIR pull request #178
Opened 2024-11-27 17:53 UTC by the-other-james

Updates the Kalman filter tutorial example. Closes #177 

The tutorial now shows what the Kalman filter plugin is doing, the data flow of the Kalman example, and steps the user through writing their own plugin to scream when something goes wrong (in the data).

2024-12-02 20:01 UTC, asgibson requested changes
Great job overall. This should go a long way to helping people get familiar with using OnAIR. I was able to follow it and implement with expected results.

2024-12-12 20:21 UTC, the-other-james commented on doc/tutorial.md
> +Note: you can set plugins to be blank or the 'generic' empty plugin.
I mean you can leave the line empty, like in the example here, or use the generic plugin which has the same effect: https://github.com/nasa/OnAIR/blob/175-finish-architecture-page-of-the-documentation/onair/config/default_config.ini#L22

2024-12-12 20:23 UTC, the-other-james commented on doc/tutorial.md
> +Note: you can set plugins to be blank or the 'generic' empty plugin.
I'll just remove the line.

2024-12-12 20:47 UTC, the-other-james commented on doc/tutorial.md
> +There is also a Learners plugin, csv output: normally a learner would use both the low-level data and the higher level information from the Knowledge Representation to TODO.
Removed, finished line.

2024-12-12 20:48 UTC, the-other-james commented on doc/tutorial.md
> +`AIPlugin` also defines an `__init__` function which stores the plugin name and a list of names of the telemetry points in the low level data (called "headers").
Updated

2024-12-12 20:48 UTC, the-other-james commented on doc/tutorial.md
> +You can see that there is now a KnowledgeRep plugin, Kalman Filter: this plugin will see the low-level data frame and use it to build up higher level information.
Fixed.

2024-12-12 20:49 UTC, the-other-james commented on doc/tutorial.md
> +We do everything in the `update` function since scream doesn't actually have anything useful to pass on to other plugins.
Explained a bit better.

2024-12-17 21:54 UTC, merged